### ISSUE TITLE
Past Broadcasts are no longer working (Script failed)

### ISSUE THREAD

**Issue by spam8117** [anxdpanic/plugin.video.twitch#108]
Since yesterday it is no longer possible to watch past broadcasts...
I`m on version 1.2.0

Thanks for your help :+1: 

10:26:24 T:2886526016  NOTICE: -->Python Interpreter Initialized<--
10:26:26 T:2886526016  NOTICE: [xbmcswift2] Request for "/channelVideos/adwcta/" matches rule for function "channelVideos"
10:26:26 T:2894914624  NOTICE: Thread BackgroundLoader start, auto delete: false
10:26:27 T:2886526016  NOTICE: Thread LanguageInvoker start, auto delete: false
10:26:27 T:2886526016  NOTICE: -->Python Interpreter Initialized<--
10:26:28 T:2886526016  NOTICE: [xbmcswift2] Request for "/channelVideosList/adwcta/0/true/" matches rule for function "channelVideosList"
10:26:29 T:2894914624  NOTICE: Thread BackgroundLoader start, auto delete: false
10:26:31 T:2886526016  NOTICE: Thread LanguageInvoker start, auto delete: false
10:26:31 T:2886526016  NOTICE: -->Python Interpreter Initialized<--
10:26:32 T:2886526016  NOTICE: [xbmcswift2] Request for "/playVideo/v3724525/" matches rule for function "playVideo"
10:26:33 T:2886526016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'live'
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 251, in <module>
                                                PLUGIN.run()
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(*_items)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 20, in wrapper
                                                return func(_args, **kwargs)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 150, in playVideo
                                                playlist = TWITCHTV.getVideoChunksPlaylist(id,videoQuality)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/twitch.py", line 138, in getVideoChunksPlaylist
                                                chunks = vidChunks['chunks'][Keys.QUALITY_LIST_VIDEO[0]]
                                            KeyError: 'live'
                                            -->End of Python script error report<--
10:26:33 T:3037458432   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/v3724525/]
10:26:33 T:2886526016  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by ingwinlu** [comment]
see #106

**Comment by Giacom** [comment]
Should this be closed?

**Comment by MrSprigster** [comment]
Fixed in #110
