### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by rafal1137** [anxdpanic/plugin.video.twitch#187]
When I did changed Kodi language in my case to Polish Twitch app stopped to play streams
I am using desktop app
Also I did get another issue all my Following streams disapeared but its not language issue

Here's log:

17:25:37 T:4112  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:25:38 T:2660  NOTICE: [xbmcswift2] Request for "/showSettings/" matches rule for function "showSettings"
17:25:54 T:4972   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/showSettings/
17:25:54 T:4972   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/showSettings/) failed
17:25:55 T:5956  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:25:56 T:960  NOTICE: [xbmcswift2] Request for "/createFollowingList/" matches rule for function "createFollowingList"
17:26:03 T:3768  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:26:04 T:3452  NOTICE: [xbmcswift2] Request for "/showSettings/" matches rule for function "showSettings"
17:26:11 T:4972   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/showSettings/
17:26:11 T:4972   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/showSettings/) failed
17:26:11 T:3496  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:26:19 T:6072 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:11688, P:61632, O:10576.
17:26:23 T:4972 WARNING: CSkinInfo: failed to load skin settings
17:26:25 T:4972   ERROR: Unable to activate the previous window
17:26:29 T:3792  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:26:31 T:1128  NOTICE: [xbmcswift2] Request for "/createFollowingList/" matches rule for function "createFollowingList"
17:26:34 T:6064  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
17:26:35 T:3064  NOTICE: [xbmcswift2] Request for "/createListOfChannels/0/" matches rule for function "createListOfChannels"
17:26:36 T:3064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u0105' in position 3: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib__run__.py", line 7, in <module>
                                                sys.exit(PLUGIN.run())
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(*_items)
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\exception.py", line 11, in wrapper
                                                return func(_args, **kwargs)
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 116, in createListOfChannels
                                                in TWITCHTV.getChannels(offset, limit)]
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\converter.py", line 118, in convertStreamToListItem
                                                info = self.getPlotForStream(stream)
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\converter.py", line 225, in getPlotForStream
                                                viewers=formatKey(Keys.VIEWERS), delay=formatKey(Keys.DELAY),
                                              File "C:\Users\Rafal\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\converter.py", line 221, in formatKey
                                                value = item_template.format(head=headings.get(thisKey), info=info.get(thisKey))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0105' in position 3: ordinal not in range(128)
                                            -->End of Python script error report<--
17:26:36 T:4972   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/createListOfChannels/0/
17:26:36 T:4972   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/createListOfChannels/0/) failed

**Comment by MrSprigster** [comment]
Fixed in https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/190
