### ISSUE TITLE
error '1080p60 - source' is not in list on twitchcon streams

### ISSUE THREAD

**Issue by killerpommes** [anxdpanic/plugin.video.twitch#203]
Hi,
the twitchcon streams are not working. I get this error

```
19:59:33 583431.187500 T:1354748912  NOTICE: [xbmcswift2] Request for "/playLive/twitchconbiblethump/-2/" matches rule for function "playLive"
19:59:35 583433.625000 T:1354748912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: u'1080p60 - source' is not in list
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/__run__.py", line 7, in <module>
                                                sys.exit(PLUGIN.run())
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/exception.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/routes.py", line 295, in playLive
                                                stream['path'] = TWITCHTV.getLiveStream(name, videoQuality)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch/api.py", line 204, in getLiveStream
                                                playlist = M3UPlaylist(data, qualityList)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch/utils.py", line 115, in __init__
                                                qualityInt = self.qualityList.index(quality)
                                            ValueError: u'1080p60 - source' is not in list
                                            -->End of Python script error report<--
19:59:35 583433.875000 T:1956299696   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/twitchconbiblethump/-2/]
```

I'am using a Raspberry Pi 2 with OSMC 2016.08-1 (Kodi 16.1)

**Comment by MrSprigster** [comment]
Thanks for reporting this. 

As Twitch seem to be regularly adding to or changing their naming of their transcodes, it may be worth adding an exception that allows the stream to play if the transcode name isn't known .

**Comment by anxdpanic** [comment]
The change in #204 skips unknowns, so future changes shouldn't grind things to a halt
