### ISSUE TITLE
Errors when trying to load channels with 2.0.0~alpha12

### ISSUE THREAD

**Issue by dazedcrazy** [anxdpanic/plugin.video.twitch#262]
Every time i try to load channels i get this error
```
12:07:54.346 T:3307324320   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
12:07:54.352 T:3307324320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "value" for method "setProperty" must be unicode or str
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/__run__.py", line 44, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/__run__.py", line 40, in main
                                                DISPATCHER.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon/common/url_dispatcher.py", line 102, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon/error_handling.py", line 33, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/routes.py", line 300, in list_followed
                                                utils.refresh_previews()
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon/utils.py", line 155, in refresh_previews
                                                set_refresh_stamp()
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon/utils.py", line 161, in set_refresh_stamp
                                                window.setProperty(key='%s-lpr_stamp' % kodi.get_id(), value=datetime.now())
                                            TypeError: argument "value" for method "setProperty" must be unicode or str
                                            -->End of Python script error report<--
```

The version is 2.0.0~alpha12 from repository.anxdpanic.testing

EDIT: the above is using LibreElec, so i tested again on windows and get the same

```
12:20:45.384 T:6608   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
12:20:45.386 T:6608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "value" for method "setProperty" must be unicode or str
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\__run__.py", line 44, in <module>
                                                sys.exit(main())
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\__run__.py", line 40, in main
                                                DISPATCHER.dispatch(mode, queries)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\common\url_dispatcher.py", line 102, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\error_handling.py", line 33, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 300, in list_followed
                                                utils.refresh_previews()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\utils.py", line 155, in refresh_previews
                                                set_refresh_stamp()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\utils.py", line 161, in set_refresh_stamp
                                                window.setProperty(key='%s-lpr_stamp' % kodi.get_id(), value=datetime.now())
                                            TypeError: argument "value" for method "setProperty" must be unicode or str
                                            -->End of Python script error report<--
```

EDIT again: after testing a little more it seems that turning off live previews fixes the problem, this only started to happen in alpha12

**Comment by anxdpanic** [comment]
Thanks, will be addressed in next alpha. Just working on re-connection logic for dropped live streams now and will PR both.

**Comment by anxdpanic** [comment]
Should be all set now! 👍
