### ISSUE TITLE
following games error

### ISSUE THREAD

**Issue by h0us3cat** [anxdpanic/plugin.video.twitch#315]
I downloaded latest clone/zip from github, when i open following games i get a error to check logs
This is in the log.

22:34:41.009 T:7004   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: _get_followed() got an unexpected keyword argument 'limit'
                                            Traceback (most recent call last):
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 1237, in <module>
                                                sys.exit(run())
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 1233, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\common\url_dispatcher.py", line 102, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\error_handling.py", line 34, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 508, in list_followed
                                                games = twitch.get_followed_games(username, offset, REQUEST_LIMIT)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\error_handling.py", line 66, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\common\cache.py", line 110, in memoizer
                                                result = func(*args, **kwargs)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\api.py", line 308, in get_followed_games
                                                results = self.api.games._get_followed(username=name, limit=limit, offset=offset)
                                              File "C:\Users\htpc1\AppData\Roaming\Kodi\addons\script.module.python.twitch\resources\lib\twitch\queries.py", line 160, in wrapper
                                                qry = f(*args, **kwargs)
                                            TypeError: _get_followed() got an unexpected keyword argument 'limit'
                                            -->End of Python script error report<--
22:34:41.078 T:6232   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/?content=games&mode=followed
22:34:41.080 T:6232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?content=games&mode=followed) failed
22:34:41.435 T:7008  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|

**Comment by anxdpanic** [comment]
you also need the latest master for the dependency. https://github.com/MrSprigster/script.module.python.twitch
