### ISSUE TITLE
Encoding problem with title of stream (non-ASCII characters)

### ISSUE THREAD

**Issue by kolinger** [anxdpanic/plugin.video.twitch#378]
Addon will cause error when non-ASCII characters are used (in title of stream in this case).

```
19:42:27.935 T:11652  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['live']| and kwargs |{}|
19:42:28.386 T:11652   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 1437, in <module>
                                                sys.exit(run())
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 1433, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\common\url_dispatcher.py", line 102, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\error_handling.py", line 32, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\routes.py", line 513, in list_followed
                                                kodi.create_item(converter.stream_to_listitem(stream))
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\converter.py", line 280, in stream_to_listitem
                                                title = self.get_title_for_stream(stream)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\converter.py", line 400, in get_title_for_stream
                                                return self.title_builder.format_title(title_values)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\utils.py", line 560, in format_title
                                                title_values[key] = self.clean_title_value(value)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\utils.py", line 579, in clean_title_value
                                                return unicode(value).replace('\r\n', ' ').strip()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--
19:42:28.447 T:11248   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/?content=live&mode=followed
19:42:28.449 T:11248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?content=live&mode=followed) failed
```
Reproduced with this character in title "✵".

Tested on:

```
Kodi (18.0-ALPHA1 Git:20180304-89a53e418e). Platform: Windows NT x86 64-bit
plugin.video.twitch v2.2.2
```
Title is already in UTF-8 but it is encoded again with function "clean_title_value". This will fail. 

Removing redundant encoding (function unicode) will resolve the issue but I have no idea about compatibility. If other systems can have different encoding. Since nobody reported this issue it seems that this can be the case. Beacuse "weird" UTF-8 characters/non-ASCII are quiet common.

Don't know how to handle this properly. Try to encode and if encoding fails then fallback to raw string?

**Comment by anxdpanic** [comment]
can you give the current master a try, #380 should hopefully resolve this

**Comment by kolinger** [comment]
Works for me. Thank you!
