### ISSUE TITLE
Access token api change -  'dict' object has no attribute 'decode'

### ISSUE THREAD

**Issue by max-te** [anxdpanic/plugin.video.twitch#460]
Since today, when trying to play any stream I get the following error: (from kodi.log)
```
2019-11-06 20:41:55.543 T:3465073536  NOTICE: Twitch: Calling |_list_followed| for mode |followed| with pos args |['live']| and kwargs |{}|
2019-11-06 20:42:01.231 T:3465073536  NOTICE: Twitch: Calling |_play| for mode |play| with pos args |[]| and kwargs |{'channel_id': '20483303'}|
2019-11-06 20:42:02.069 T:3465073536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 157, in _play
                                                play.route(twitch_api, seek_time, channel_id, video_id, slug, ask, use_player, quality, channel_name)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/play.py", line 116, in route
                                                videos = api.get_live(name)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 80, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/cache.py", line 104, in memoizer
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/api.py", line 325, in get_live
                                                results = self.usher.live(name)
                                              File "/storage/.kodi/addons/script.module.python.twitch/resources/lib/twitch/parser.py", line 51, in m3u8_wrapper
                                                results = results.decode('utf-8')
                                            AttributeError: 'dict' object has no attribute 'decode'
                                            -->End of Python script error report<--
2019-11-06 20:42:02.265 T:4089800528   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=20483303&mode=play]
```

The seems to be, that the api endpoint for access tokens has been changed or removed. Streamlink has the same issue https://github.com/streamlink/streamlink/issues/2680

**Comment by max-te** [comment]
Aaaand it seems to work as before again. Let's hope this was just a Twitch hiccup.

**Comment by deridiot** [comment]
well it's bck with a vengeance

looking at the results object:
{'error': 'Gone', 'status': 410, 'message': 'this API has been removed.'}

**Comment by fragande** [comment]
> 
> 
> well it's bck with a vengeance
> 
> looking at the results object:
> {'error': 'Gone', 'status': 410, 'message': 'this API has been removed.'}

See #461. Detailed workaround: https://github.com/MrSprigster/Twitch-on-Kodi/issues/461#issuecomment-552670340.
