### ISSUE TITLE
Nothing plays after ~9pm local time (gmt +2), every day

### ISSUE THREAD

**Issue by pitsi** [anxdpanic/plugin.video.twitch#462]
As the title suggests, I have this major issue with twitch for the last 4+ days. Here is a small part of the log file
```
2019-11-06 21:13:05.991 T:139746273646336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 157, in _play
                                                play.route(twitch_api, seek_time, channel_id, video_id, slug, ask, use_player, quality, channel_name)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/play.py", line 116, in route
                                                videos = api.get_live(name)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 80, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/cache.py", line 104, in memoizer
                                                result = func(*args, **kwargs)
                                              File "/home/jim/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/api.py", line 325, in get_live
                                                results = self.usher.live(name)
                                              File "/home/jim/.kodi/addons/script.module.python.twitch/resources/lib/twitch/parser.py", line 51, in m3u8_wrapper
                                                results = results.decode('utf-8')
                                            AttributeError: 'dict' object has no attribute 'decode'
                                            -->End of Python script error report<--
2019-11-06 21:13:06.036 T:139747871482240   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=62509474&mode=play]
2019-11-06 21:13:53.979 T:139746265253632 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
2019-11-06 21:13:54.391 T:139746265253632  NOTICE: Twitch: Calling |_game_lists| for mode |game_lists| with pos args |['Mortal Kombat 11']| and kwargs |{}|
2019-11-06 21:13:54.400 T:139746558867200   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?game=Mortal%20Kombat%2011&mode=game_lists
2019-11-06 21:13:54.405 T:139747871482240   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?game=Mortal%20Kombat%2011&mode=game_lists) failed
2019-11-06 21:13:54.514 T:139746265253632   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/
2019-11-06 21:13:54.514 T:139747871482240   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/) failed
2019-11-06 21:13:54.516 T:139746265253632   ERROR: Unable to find plugin
2019-11-06 21:13:54.516 T:139746265253632   ERROR: GetDirectory - Error getting plugin://
2019-11-06 21:13:54.516 T:139747871482240   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
```
No live stream plays, regardless of game or resolution and no clips play too! If i start a live stream at e.g. 8.30pm it plays fine. I have tried with downgrading to 2.4.4 and resetting function cache and deleting storage.json from the maintenance menu, but no luck.

Checked on libreelec 9.2beta2 and on debian testing. Both are x64 installations and both use kodi 18.4 and their settings are the same.

p.s. No full log will be given because I use some addons which I do not want to share with the rest of the world.

**Comment by anxdpanic** [comment]
see #461
