### ISSUE TITLE
No Playback - inputstream.adaptive 2.4.3.1

### ISSUE THREAD

**Issue by ValenVanHel** [anxdpanic/plugin.video.twitch#489]
Hey, got a Problem here... 
its happened with all addons which play with inputstream.adaptive 2.4.2.

Twitch-Addon is just a example. Maybe helps to say that.

```
2020-02-29 11:30:23.299 T:3012053472  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.twitch/?channel_id=47627824&mode=play
2020-02-29 11:30:23.300 T:2388366192  NOTICE: Creating InputStream
2020-02-29 11:30:23.302 T:2388366192   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.4.2
2020-02-29 11:30:23.303 T:2388366192   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2020-02-29 11:30:23.303 T:2388366192   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.twitch/?channel_id=47627824&mode=play]
2020-02-29 11:30:23.303 T:2388366192  NOTICE: CVideoPlayer::OnExit()
2020-02-29 11:30:23.400 T:2691076976   ERROR: EXCEPTION: XBMC is not playing any file
2020-02-29 11:30:23.401 T:2691076976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/player.py", line 77, in onPlayBackStarted
                                                is_playing = any(host_match in self.getPlayingFile() for host_match in twitch_host_matches)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/player.py", line 77, in <genexpr>
                                                is_playing = any(host_match in self.getPlayingFile() for host_match in twitch_host_matches)
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--
2020-02-29 11:30:23.433 T:3012053472  NOTICE: CVideoPlayer::CloseFile()
2020-02-29 11:30:23.433 T:3012053472  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-29 11:30:23.433 T:3012053472  NOTICE: VideoPlayer: finished waiting`
```

So i see the inputstream.adaptive.so.2.4.2 is missing, but why... at 1 oclock works anything fine! And inputstream.adaptive 2.4.3.1 from peak3d is installed.

Greetings

**Comment by anxdpanic** [comment]
This would be something system, or inputstream.adaptive related. I would try to reinstall inputstream.adaptive depending on your system.
