### ISSUE TITLE
Sometimes crashes with index out of range

### ISSUE THREAD

**Issue by peol** [anxdpanic/plugin.video.twitch#5]
```
18:00:57 T:2826953824  NOTICE: [xbmcswift2] Request for "/playLive/kungentv/" matches rule for function "playLive"
18:00:59 T:2826953824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.twitch/default.py", line 308, in <module>
                                                plugin.run()
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 311, in run
                                                return self._dispatch(self.request.path)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 288, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.xbmc/addons/plugin.video.twitch/default.py", line 290, in playLive
                                                jtvtoken = getBestJtvTokenPossible(name)
                                              File "/storage/.xbmc/addons/plugin.video.twitch/default.py", line 260, in getBestJtvTokenPossible
                                                return data[bestIndex]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:00:59 T:3044315136   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/kungentv/]
```

Running on openelec (raspberry pi).

**Comment by StateOfTheArt89** [comment]
Hey peol,
are you able to reproduce the error in certain situations? There is a new commit pushed to the repo which should solve this kind of a problem.

**Comment by peol** [comment]
Hey @StateOfTheArt89, I'll try it out, thanks!

There seems to be playlist failures every other time I try to play a stream as well. They're also sometimes hanging (i.e. you get a picture but then it freezes and you have stop playback and retry, could take 10-15 times before it actually starts playing). A reboot often fixes those issues directly. I'll try to track down a debug log of that, seems to be a separate issue. :)

**Comment by peol** [comment]
These issues seems to have been XBMC-related, works now. Closing it.
