### ISSUE TITLE
Fresh LibreElect Install : impossible to view live channels : exceptions.UnicodeDecodeError

### ISSUE THREAD

**Issue by ledshark24** [anxdpanic/plugin.video.twitch#508]
Hi,

I can no longer view any stream (live or old) using the plugin. 
I made a fresh LibreELEC install with the plugin. Just added a fresh token.
same behavior : i can navigate my subscriptions but i can't view any video.

here is what i believe are the relevant logs :

```
2020-05-15 19:35:31.986 T:1379836800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 101, in _list_followed
                                                followed.route(twitch_api, content, offset, cursor)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py", line 76, in route
                                                kodi.create_item(converter.stream_to_listitem(stream))
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 265, in stream_to_listitem
                                                context_menu.extend(menu_items.channel_videos(channel[Keys._ID], channel[Keys.NAME], name))
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/menu_items.py", line 43, in channel_videos
                                                return update_container(i18n('go_to') % ''.join(['[COLOR=white][B]', display_name, '[/B][/COLOR]']),
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-05-15 19:35:31.987 T:1379836800   DEBUG: onExecutionDone(32, /storage/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py)
2020-05-15 19:35:32.061 T:1937711120   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-05-15 19:35:32.208 T:1379836800    INFO: Python interpreter stopped
2020-05-15 19:35:32.209 T:1379836800    INFO: Previous line repeats 3 times.
2020-05-15 19:35:32.209 T:1379836800   DEBUG: Thread LanguageInvoker 1379836800 terminating
2020-05-15 19:35:32.222 T:1488941952   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?content=live&mode=followed
```
Do not hesitate to ask for more information, I will be happy to help.
this is on a 2.5.0 version of the extension.

**Comment by anxdpanic** [comment]
I need the debug information before this error so I can see the content that is causing it.

**Comment by ledshark24** [comment]
Hi,
this is a first logfile with an old attempt : [log1](https://0bin.net/paste/EblYpMAG8xyqnk0X#jLWRQPjYAO20+0xL3fWSD6Xn2Qk0qVCwAASJrwjzh09)
and this is a fresh triple attempt [log2](https://framabin.org/p/?cea4119c9226f9c3#dcdlBabPGUTXH06Fou3RQ9Uu+XJujQdE37hrt8pF8oU=) with 3 attempts 
I hope it will help.

**Comment by anxdpanic** [comment]
beta1 zip should resolve the issue: 
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.x.x-dev
This issue surfaced with the fr_fr translation, and since I use en_us I may have missed something, please let me know if you notice any new issues surface.

**Comment by ledshark24** [comment]
Hi, 
I just installed the beta via the zip file the issue is no longer present. Many thanks. I will be more attentive to the extension behavior in the next days.
many thanks again.

**Comment by anxdpanic** [comment]
Thanks for testing and confirming.
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.1
Fix is submitted for review to official repository, you should receive the update like usual when it's available 👍
