### ISSUE TITLE
Since 2.5.0 install - Unable to play any video (live or replays) - OSMC

### ISSUE THREAD

**Issue by MadDeydey** [anxdpanic/plugin.video.twitch#509]
Hello,

Since i update the app to 2.5.0, i'm not able to play any video : live or any replay.
Here, you will find a log including 2 tries (live & replay search)

[debug.log](https://github.com/MrSprigster/Twitch-on-Kodi/files/4638056/debug.log)

If you need anything else, i'll try to react fast.

**Comment by AlexSchieving** [comment]
Same here, I paste you my log in hope that it helps: https://ares-project.uk/logupload/log.php?id=269692

**Comment by feuille2lune** [comment]
I've the same symptom with this message in my kodi.log : 

2020-05-16 12:09:09.317 T:3476419456 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
2020-05-16 12:09:12.744 T:3476419456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 101, in _list_followed
                                                followed.route(twitch_api, content, offset, cursor)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py", line 76, in route
                                                kodi.create_item(converter.stream_to_listitem(stream))
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 265, in stream_to_listitem
                                                context_menu.extend(menu_items.channel_videos(channel[Keys._ID], channel[Keys.NAME], name))
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/menu_items.py", line 43, in channel_videos
                                                return update_container(i18n('go_to') % ''.join(['[COLOR=white][B]', display_name, '[/B][/COLOR]']),
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-05-16 12:09:12.932 T:3496543104   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?content=live&mode=followed
2020-05-16 12:09:12.951 T:4086777680   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?content=live&mode=followed) failed
2020-05-16 12:09:13.099 T:3476419456 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|

My twitch and twitch-script extensions are up to date on 2 devices odroid C2 and N2. The symptoms are the same on twice.

**Comment by Brownie2002** [comment]
Hello, same here, same log.

**Comment by anxdpanic** [comment]
beta1 zip should resolve the issue: 
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.x.x-dev
This issue surfaced with the fr_fr translation, and since I use en_us I may have missed something, please let me know if you notice any new issues surface.

**Comment by Brownie2002** [comment]
Ok for me. It was the french translation also ! Thank You. I tested : plugin.video.twitch-2.5.1.beta1.zip I donn't know what are the other files. But congrats for the reactivity.

**Comment by MadDeydey** [comment]
Hello anxdpanic.

I'm sorry, i forgot to tell you that it was in french...
It seems that the beta repairs all the problems described.
Well done! and thank you for your reactivity :)

**Comment by anxdpanic** [comment]
Thanks for confirming!

@Brownie2002 +matrix versions are for Kodi 19, -unofficial uses a cache cleaner to clean stream thumbnails, this isn't allowed in the official repository so 'unofficial'.

**Comment by feuille2lune** [comment]
Hi I tested on coreelec 9.2.1 (kodi leia) and it works well for live and replay.

Thx @anxdpanic
