### ISSUE TITLE
Error when trying to watch stream

### ISSUE THREAD

**Issue by CubeStick** [anxdpanic/plugin.video.twitch#543]
Hi, I'm getting an error when trying to watch a stream on my raspberry pi 4 with Kodi and this add-on.
Using the latest Kodi and latest version of the add-on all on default settings.
Here's the error in the log:

`2021-01-22 18:09:47.239 T:2619843440 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
2021-01-22 18:09:48.207 T:3011508704  NOTICE: Samba is idle. Closing the remaining connections
2021-01-22 18:09:53.080 T:2619843440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 0
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 157, in _play
                                                play.route(twitch_api, seek_time, channel_id, video_id, slug, ask, use_player, quality, channel_name)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/play.py", line 117, in route
                                                videos = api.get_live(name)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 81, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/cache.py", line 104, in memoizer
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/api.py", line 329, in get_live
                                                results = self.usher.live(name, headers=self.get_private_credential_headers())
                                              File "/storage/.kodi/addons/script.module.python.twitch/resources/lib/twitch/parser.py", line 50, in m3u8_wrapper
                                                results = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.python.twitch/resources/lib/twitch/api/usher.py", line 136, in live
                                                token = token[0][keys.DATA][keys.STREAM_PLAYBACK_ACCESS_TOKEN]
                                            KeyError: 0
                                            -->End of Python script error report<--
2021-01-22 18:09:53.174 T:3011508704   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=30967548&mode=play]`

**Comment by ynizon** [comment]
same problem for me

**Comment by Dekat** [comment]
Same here ! I just removed the "Private OAuth API token" and it worked.
