### ISSUE TITLE
no connection to the Twitch API.

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#690]
### Context

Please provide any relevant information about your setup

* Add-on Version: 3.0.2
* Kodi Version: 20.2.0
* Kodi GUI Language: Russian
* Operating System: Windows 11 pro (22h2)
* Operating System Language: Russian

------

### Expected Behavior

...

------

### Current Behavior

When I try to log into the addon, it says that there is no connection to the Twitch API.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. running Kodi
2. trying to run an addon

------

### Log

Please include a complete 
```
2023-10-12 00:54:33.618 T:2664     info <general>: Skipped 2 duplicate messages..
2023-10-12 00:54:33.618 T:2664    error <general>: Traceback (most recent call last):
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>:   File "C:\Users\Prototype\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\router.py", line 290, in run
                                                       twitch_api = api.Twitch()
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>:   File "C:\Users\Prototype\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\api.py", line 50, in __init__
                                                       if not self.valid_private_token(self.private_client_id, self.private_access_token):
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>:   File "C:\Users\Prototype\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\common\cache.py", line 103, in memoizer
                                                       result = func(*args, **kwargs)
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>:   File "C:\Users\Prototype\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\api.py", line 111, in valid_private_token
                                                       if token_check['client_id'] != self.private_client_id:
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>: KeyError: 'client_id'
                                                   
2023-10-12 00:54:33.619 T:2664    error <general>: 
2023-10-12 00:54:33.619 T:2664    error <general>: Twitch: None
```

------

### Additional Information

It all started on October 9-10, 2023

------

**Comment by ghost** [comment]
Sorry I was inattentive. problem solved please close

**Comment by Boronsbruder** [comment]
How did you solve it? 
I have the same Problem here after upgrading to Nexus

Solved it too now.
You need to update the oauth-token in "subscriber / Twitch Turbo"
