### ISSUE TITLE
Traceback erro in getBestJtvTokenPossible

### ISSUE THREAD

**Issue by jdarmst** [anxdpanic/plugin.video.twitch#75]
my version is 0.2.2 and this is what comes up in xbmc.log when I try to play a stream.

17:06:20 T:140118096406272  NOTICE: -->Python Interpreter Initialized<--
17:06:26 T:140118096406272   ERROR: Error Type: <type 'exceptions.IndexError'>
17:06:26 T:140118096406272   ERROR: Error Contents: list index out of range
17:06:26 T:140118096406272   ERROR: Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.video.twitch/default.py", line 342, in <module>
                                                playLive(channelname)
                                              File "/home/xbmc/.xbmc/addons/plugin.video.twitch/default.py", line 304, in playLive
                                                jtvtoken = getBestJtvTokenPossible(name)
                                              File "/home/xbmc/.xbmc/addons/plugin.video.twitch/default.py", line 278, in getBestJtvTokenPossible
                                                return data[bestIndex]
                                            IndexError: list index out of range
17:06:26 T:140118935803776   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?url=...&mode=play&channelname=dansgaming]

**Comment by MrSprigster** [comment]
0.2.2 is a very old version and is no longer supported. Please upgrade to the latest version 1.1.3 and your issues will magically disappear.
